### ISSUE TITLE
It doesn't start on Ubuntu 16.10

### ISSUE THREAD

**Issue by ricsipontaz** [kasramp/UbuntuIndicatorWeather#22]
It doesn't start on a freshly installed Ubuntu 16.10
Error Message:

`/usr/bin/indicator-weather:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appIndicator
Traceback (most recent call last):
  File "/usr/bin/indicator-weather", line 144, in <module>
    indicator = WeatherIndicator()
  File "/usr/bin/indicator-weather", line 63, in __init__
    self.configuration = Configuration()
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 29, in __init__
    self.ini_start_up = self.__create_start_up_script_if_not_exist()
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 49, in __create_start_up_script_if_not_exist
    if exc.errno != errno.EEXIST:
NameError: global name 'errno' is not defined
`
Ubuntu 16.10
Linux 4.8.0.27
Python 2.7.12
Indicator-Weather 0.8-1ubuntu2

**Comment by kasramp** [comment]
Fixed in v0.8.2

**Comment by ricsipontaz** [comment]
Thanks, it is working now :) :+1:
