### ISSUE TITLE
Indicator stopped working after installing tlp on 17.10

### ISSUE THREAD

**Issue by martinhajek** [kasramp/UbuntuIndicatorWeather#54]
After having installed tlp (Linux Advanced Power Management), the weather indicator stopped working. When I try to launch it via terminal it gets stuck. After a while, when I hit Ctrl+C, it gives this:
^CTraceback (most recent call last):
  File "/usr/bin/indicator-weather", line 259, in <module>
    indicator.main()
  File "/usr/bin/indicator-weather", line 140, in main
    self.get_weather()
  File "/usr/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/retrying.py", line 220, in call
    time.sleep(sleep / 1000.0)
KeyboardInterrupt

Is there any possiblity to make it work again? Thanks

**Comment by kasramp** [comment]
Did you manage to resolve the issue?
